name: Reuse Vale from Mkdocs repo

on:
  issue_comment:
    types: [created]

jobs:
  reuse-vale:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/vale-review')
    permissions:
      pull-requests: write
    uses: 0xlucca/polkadot-mkdocs/.github/workflows/reusable-vale-V2.yml@main
    with:
      repo: ${{ github.repository }}
      pr_number: ${{ github.event.issue.number }}
      commit_sha: ${{ github.event.pull_request.head.sha }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
