name: Local Vale

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  pull_request:
    branches: main

jobs:
  review-docs-from-vale:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    outputs:
      files: ${{ steps.get-modified-files.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 0xLucca/polkadot-docs-test

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 0xLucca/polkadot-mkdocs
          sparse-checkout: |
            .github/styles
            .vale.ini
          sparse-checkout-cone-mode: false
          path: vale

      - name: Move Vale files
        run: |
          mv vale/.vale.ini .
          mv vale/.github/styles .github/styles

      - name: Install tree and use it
        run: sudo apt-get install -y && tree

      - name: Get modified files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: get-modified-files
        run: |
          changed_files=$(gh pr diff --repo ${{ github.repository }} --name-only ${{ github.event.pull_request.number }} | grep '\.md$' || true)
          md_files=$(echo "$changed_files" | jq -R -s 'split("\n")[:-1]' | jq -c .)
          echo "Modified md files: $md_files"
          echo "files=$md_files" >> $GITHUB_OUTPUT

      - name: Review docs
        if: ${{ steps.get-modified-files.outputs.files != '[""]' }}
        uses: errata-ai/vale-action@reviewdog
        with:
          files: ${{ steps.get-modified-files.outputs.files }}
          reporter: github-pr-review
          fail_on_error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REVIEWDOG_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}
