name: Reuse Vale from Mkdocs repo

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  pull_request:
    branches: main

jobs:
  reuse-vale:
    uses: 0xlucca/polkadot-mkdocs/.github/workflows/reusable-vale.yml@main